LineLength:
  Max: 500
AsciiComments:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
# prevent false positive for the Chef lazy DSL syntax
AmbiguousBlockAssociation:
  Enabled: false
