LineLength:
  Max: 500
AsciiComments:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
# prevent false positive for the Chef lazy DSL syntax
AmbiguousBlockAssociation:
  Enabled: false
# delimeters changed across rubocop versions we test with, so must disable
Style/PercentLiteralDelimiters:
  Enabled: false
